apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deploy
  namespace: signals
  labels:
    projectName: signals
spec:
  selector:
    matchLabels:
      run: signals
  replicas: 1
  template:
    metadata:
      labels:
        run: signals
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:3.8
        ports:
        - containerPort: 2181
        env:
          - name: ALLOW_ANONYMOUS_LOGIN
            value: 'yes'
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc
  labels:
    projectName: signals
spec:
  ports:
  - port: 2181
    protocol: TCP
  selector:
    run: signals
  